name: Publish on npmjs.org

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [ 24 ]
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          version: 11
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
      - run: pnpm publish -r --no-git-checks --provenance --access public
